-- INSERT INTO USERS ()
-- INSERT INTO PLAYED_GAMES ()
-- INSERT INTO FRIEND ()
-- INSERT INTO DIFFICULTIES()
-- INSERT INTO ACHIEVEMENT_CRITERIA () VALUES ()
-- INSERT INTO ACHIEVEMENTS () VALUES ()

INSERT INTO USERS (username, password, email) VALUES ('testUser', 'password', 'testPassword');


